export default [
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
    {
        name: "Grunt",
        cost: 1,
        attack: 1,
        health: 3,
        bg: "./cards/bg/grunt-major.jpg",
    },
];
