export default [
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
    {
        name: "Marine",
        cost: 1,
        attack: 2,
        health: 2,
        bg: "./cards/bg/marine.jpg",
    },
];
